#!/usr/bin/env bash

# Generating a new SSH key and adding it to the ssh-agent
# https://docs.github.com/en/enterprise/2.17/user/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
# sudo ssh-keygen -t rsa -b 4096 -C "email"
# Enter file in which to save the key (/root/.ssh/id_rsa): /usr/local/share/.ssh/id_rsa
# 1. After creating the ssh key, fetch and copy the content of the id_rsa.pub file to your github-clipboard
# $ xclip -sel clip < /usr/local/share/.ssh/id_rsa.pub (if xclip its not working use only cat)
# $ cat /usr/local/share/.ssh/id_rsa.pub
# 2. And then use this to default your login method to use ssh keys instead of your credentials
# $ git config --global url.ssh://git@github.com/.insteadOf https://github.com/
# $ git pull and follow the instructions

#  if .ssh directory doesn't exist:
if [ ! -d /usr/local/share/.ssh/ ]; then
  cd /usr/local/share && sudo -s mkdir .ssh \
    && sudo -s chmod 700 ./.ssh/ \
    && sudo -s chown --recursive "${USERNAME}":"${USERNAME}" ./.ssh/
fi

#  if known_hosts directory doesn't exist:
if [ ! -d /usr/local/share/.ssh/known_hosts/ ]; then
  cd /usr/local/share/.ssh && sudo -s mkdir known_hosts/ \
    && sudo -s chmod 700 ./known_hosts/ \
    && sudo -s chown --recursive "${USERNAME}":"${USERNAME}" ./known_hosts/
fi

sudo -s apt-get update -y \
  && sudo -s apt-get install xclip -y
